### ISSUE TITLE
javax.crypto.IllegalBlockSizeException: Data must not be longer than 86 bytes

### ISSUE THREAD

**Issue by smileytechguy** [simon-weber/gpsoauth#15]
Hi,
I have a very long password and am getting this error.  What can I do to fix?

**Comment by simon-weber** [comment]
Hm, I can't imagine why you'd be getting a java exception. Are you sure you're using this python library? Can you provide a full traceback?

**Comment by smileytechguy** [comment]
Oops wrong lib - sorry

**Comment by simon-weber** [comment]
Haha, no problem.

**Comment by smileytechguy** [comment]
It was part of something else and just looked for something with the name :p
