### ISSUE TITLE
Omitting android_id in master login causes a new device entry

### ISSUE THREAD

**Issue by gough** [simon-weber/gpsoauth#2]
Omitting android_id when performing a master login causes a new device entry for each time that it is run.

![image](https://cloud.githubusercontent.com/assets/1562560/8026556/e04307ca-0d2f-11e5-8423-8758c2f2e92f.png)

**Comment by simon-weber** [comment]
Definitely not intended, haha.

I'm thinking when I expose android_id again I'll do something like the musicmanager and generate an id from the mac address if possible (eg when not on a vps).

**Comment by simon-weber** [comment]
android_id is required again as of 91acfd4e34075f0997bfaafa87c3d2088bb733e1.

It seems that the field is less strict than I thought: a 12-character id works fine, so they should be able to be created from mac addresses with little risk of collision.
