### ISSUE TITLE
Publish the new version

### ISSUE THREAD

**Issue by KapJI** [simon-weber/gpsoauth#36]
@simon-weber thanks for reviewing all my PRs! I think that was all I wanted to do here, can you please publish the updated version on PyPI so we can use it in our project?

**Comment by simon-weber** [comment]
Yup, I should be able to get to it within a day or two.

**Comment by simon-weber** [comment]
Ok, it's up! https://pypi.org/project/gpsoauth/1.0.0/

Thanks again for you contributions!
