### ISSUE TITLE
Clarify 'Error': 'NeedsBrowser'

### ISSUE THREAD

**Issue by B16f00t** [simon-weber/gpsoauth#37]
When you enter an .edu account linked to Gsuite,
Displays: 'Error': 'NeedsBrowser.

{'Error': 'NeedsBrowser', 'Url': 'https://correo.XXXXXXXXXX.edu.co:8443/cloudkey/a/XXXXXX.edu.co/index?SAMLRequest=fVJLT%2BMwEL6vxH%2BIfM%2BrCLSymqACQlQCNqKBAzfjTFKD7Qkeu9399%2BumIOBAr59nvpdnfvbX6GQDjhTaipVZwRKwEjtlh4o9tFfpb3ZWH/2akzB65Ivg1/Ye3gKQT%2BKmJT49VCw4y1GQIm6FAeJe8tXi9obPsoKPDj1K1CxZXlZMohXrzhgNuh/wtRsGNC9iRCtBDAIV9IPupAWWPH7Ymu1sLYkCLC15YX2EilmZFqfp7LQtT3h5zIviiSXNu9K5svsEh2w974eIX7dtkzZ/Vu1EsFEduLs4XbEBcdCQSTQ7%2BUYQqU2Ee6Ep2lsQgfPR4AVaCgbcCtxGSXi4v6nY2vuReJ5vt9vskyYXebDPSLHADLoQoVxIYvVUL58Sui%2B9HvYvPvRZfUhhnn8hr98/cpdvedmgVvJfstAatxcOhI/hvAsx2xU6I/zP%2BmVWTojq0n4a5cHSCFL1CjqW5PVe9fvFxDv6Dw%3D%3D&RelayState=https://accounts.google.com/CheckCookie?continue%3Dhttps://accounts.google.com/o/android/auth?hl%253Den_us%2526xoauth_display_name%253DAndroid%252BLogin%252BService%2526source%253DAndroid%252BLogin', 'ErrorDetail': 'To access your account, you must sign in on the web. Touch Next to start browser sign-in.'}

**Comment by simon-weber** [comment]
This is a bit of a misleading response from Google. Nothing really went wrong, but Google has determined for whatever reason that they need you to log in through a web browser. In your case, it looks like your institution has their own custom login system. I've also seen this happen when Google thinks a log in attempt is suspicious.

You should be able to copy and paste that url into a browser and continue from there.

We could document this better, but I'm not sure there's anything else we can do to improve this case on gpsoauth's end.

**Comment by B16f00t** [comment]
It would be nice to try to capture the token when you click on the browser to complete the login or something like that.  I could provide you with an account for testing if you wish.

**Comment by simon-weber** [comment]
That would be nice, but I think I'd rather not add the complexity of browser automation to the library.

I'll leave this open to track improving the ux, though.

**Comment by emma-eva** [comment]
Its a captcha issue. You can bypass this by click continue button... Click this link and click continue button: [https://accounts.google.com/b/0/DisplayUnlockCaptcha](https://accounts.google.com/DisplayUnlockCaptcha)

**Comment by B16f00t** [comment]
It's been two days since Google can't be accessed through this library
The error returns:
Error': 'NeedsBrowser', ''ErrorDetail': 'To access your account, you must sign in on the web. Touch Next to start browser sign-in.'}

**Comment by simon-weber** [comment]
Yeah, this looks new. The 'Url' key from the did get me to a login screen that worked, but didn't actually complete the OAuth flow. DisplayUnlockCaptcha didn't seem to work either.

**Comment by B16f00t** [comment]
Someone commented in some forum that these parameters make the authentication flow.
https://gitlab.com/AuroraOSS/AuroraStore/-/blob/master/app/src/main/java/com/aurora/store/util/AC2DMTask.kt#L27-43
I have not been able to check it.

**Comment by Deathbot64** [comment]
having the same issue with a fresh install

**Comment by emma-eva** [comment]
i fixed. But on php. I will fix on python and pull it on here.

**Comment by leikoilja** [comment]
@emma-eva, can you please share your findings with us?

**Comment by B16f00t** [comment]
I solved it in python, you can see the code in [Whapa](https://github.com/B16f00t/whapa) tool, the whagodri.py library

**Comment by simon-weber** [comment]
I've merged that and it seems to work fine for me! I'll look to cut a release today or tomorrow to include https://github.com/simon-weber/gpsoauth/commit/1bf49e91289d9f9676efd5a0d73fed7e5766df91.

**Comment by leikoilja** [comment]
Awesome news! Thanks @CyberAltra & @simon-weber ⭐ 💥 🔥

**Comment by B16f00t** [comment]
Works perfect, I think this thread could be closed by now

**Comment by simon-weber** [comment]
Released in 1.0.1.

**Comment by B16f00t** [comment]
I think it would be a good idea to add a function for OAuth authentication, like the one I posted above, because GSuite accounts keep crashing and the user could take the cookie from his browser and login this way.

**Comment by simon-weber** [comment]
That's probably reasonable. Want to open a new issue to track it?

**Comment by B16f00t** [comment]
The beginning of this issue was for this reason, for example in my program to make this type of accounts work, I had to take your library and modify it by adding a function to log in with the browser, so I contemplate all the scenarios.

**Comment by 89z** [comment]
https://github.com/simon-weber/gpsoauth/issues/44
