### ISSUE TITLE
How to use ciphers in php call?

### ISSUE THREAD

**Issue by emma-eva** [simon-weber/gpsoauth#38]
Will ssl ciphers work in php/curl? How can i use your ciphers in my php code to get token and work post method perfectly?

**Comment by simon-weber** [comment]
I'm not a php guy, but the names of the ciphers are standardized and ought to work with any http client that allows you to configure them. You might also need the alpn and no_ticket settings; you can refer to https://github.com/simon-weber/gpsoauth/pull/25 to see the settings in one place.
