### ISSUE TITLE
Passwd field works as an alternative to EncryptedPasswd

### ISSUE THREAD

**Issue by 89z** [simon-weber/gpsoauth#39]
I see here that the password is being encrypted:

https://github.com/simon-weber/gpsoauth/blob/36f1d393e047b5c62e917b1b2108fd8ffe01d7cf/gpsoauth/__init__.py#L127-L129

that is fine, but it does add some significant complexity to the code. I noticed today that you can still send plain password, if someone wants to do that. Here is an example request:

~~~
POST /auth HTTP/1.1
Host: android.clients.google.com
Content-Type: application/x-www-form-urlencoded

Email=YOUR_EMAIL&Passwd=YOUR_PASSWORD&client_sig=&droidguard_results=
~~~

You still need the same TLS setup, but otherwise this seems to simplify things quite a bit.

**Comment by 89z** [comment]
https://github.com/simon-weber/gpsoauth/issues/21

**Comment by 89z** [comment]
https://github.com/simon-weber/gpsoauth/issues/17

**Comment by 89z** [comment]
https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/61

**Comment by 89z** [comment]
https://github.com/leikoilja/ha-google-home/issues/430

**Comment by 89z** [comment]
https://github.com/GoneToneStudio/node-google-play-api/issues/6

**Comment by 89z** [comment]
https://github.com/kagasu/GooglePlayStoreApi/issues/6

**Comment by simon-weber** [comment]
Interesting! Nice find!

This would definitely simplify the code, but I'm hesitant to switch from the current EncryptedPasswd setup if it continues to work. We could put Passwd behind a flag for people to opt into it, but I'm not sure there's actually an advantage to end users (unless we made dependencies optional, maybe).

**Comment by 89z** [comment]
I was able to strip some dependencies in my implementation. In my case, it was all standard library, but still useful in my opinion.

**Comment by 89z** [comment]
closing for lack of interest
