### ISSUE TITLE
PyCrypto install/uninstall problems on Windows

### ISSUE THREAD

**Issue by thebigmunch** [simon-weber/gpsoauth#4]
As mentioned a long time ago in IRC, PyCrypto installation through pip will fail for most due to not having the [correct compiler](https://www.microsoft.com/en-us/download/details.aspx?id=44266) (for Python 2) installed. There is no separate package for Python 3, unfortunately, and I forget which compiler version is needed.

One method to get around this is to grab pre-built binaries available. This can cause issues because pip has deprecated (and will remove) the uninstallation of distutils projects:

```
DEPRECATION: Uninstalling a distutils installed project (pycrypto) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
```

So users who first install PyCrypto through pre-built binaries may not be able to properly update this dependency through pip in the future without uninstalling through Windows first even if they installed the correct compiler.

While I feel trying to port over to [cryptography](https://cryptography.io/en/latest/) or some other alternative eventually is the best plan, I figured I'd post an issue giving some information and possible solutions to any Windows users who might come across these problems.

**Comment by simon-weber** [comment]
Nice, thanks for the information. 

I started with _cryptography_ and then switched to pycrypto because of this interface: https://github.com/simon-weber/gpsoauth/blob/df83c869c7f29b5913262c4449f5d4e0d72123eb/gpsoauth/google.py#L19. There's probably some way to do that, but I didn't see it among _cryptography_'s higher-level interfaces.

**Comment by thebigmunch** [comment]
[Here's](https://github.com/dlitz/pycrypto/issues/110) another fun PyCrypto issue on Windows that some may encounter in Python 3. An alternative to porting everything to cryptography would be to support [pycryptodome](https://pypi.python.org/pypi/pycryptodome) which is a fork of PyCrypto that has actual work being done on it and has wheels available. PyCrypto has not had any work done to it in over 1.5 years.

Also, the compiler needed for 3.5 is included in the Visual C++ tools installed with [Visual Studio 2015](https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx). There is a free community edition.

**Comment by thebigmunch** [comment]
From my quick tests, pycryptodome seems to work as a drop-in replacement.

**Comment by simon-weber** [comment]
I'd be fine with that switch.
