### ISSUE TITLE
AttributeError: module 'urllib3.util.ssl_' has no attribute 'OP_NO_TICKET'

### ISSUE THREAD

**Issue by bergercookie** [simon-weber/gpsoauth#43]
I'm trying to run the latest version of `gpsoath` to see if I can get around [this issue](https://github.com/kiwiz/gkeepapi/issues/123) with gkeepapi. After explicitly upgrading to the latest `gpsoauth` version I'm getting the following error:

```
  File "/home/berger/.cache/pypoetry/virtualenvs/taskwarrior-syncall-mK6ZpwPC-py3.8/lib/python3.8/site-packages/gpsoauth/__init__.py", line 70, in init_poolmanager
    context.options &= ~ssl_.OP_NO_TICKET
    │       │           └ <module 'urllib3.util.ssl_' from '/home/berger/.cache/pypoetry/virtualenvs/taskwarrior-syncall-mK6ZpwPC-py3.8/lib/python3.8/s...
    │       └ <property object at 0x7f91b5d84680>
    └ <gpsoauth.SSLContext object at 0x7f91b0d901c0>

AttributeError: module 'urllib3.util.ssl_' has no attribute 'OP_NO_TICKET'
```

Explicitly upgrading `urllib3` from `1.25.11` to `1.26.9` inside my virtualenv seems to solve it. My guess is that you should be bumping the `requests` version [here](https://github.com/simon-weber/gpsoauth/blob/master/pyproject.toml#L26=) to a more recent one.

**Comment by simon-weber** [comment]
Good find!

It looks like urllib3 wrapped the built in ssl flag for python <3.6 compat ([here](https://github.com/urllib3/urllib3/commit/ed628df10b2810b9bf1e02aca0adb23ea4f4d977)). Since we're not supporting 3.6 we should be good to use it directly.
