### ISSUE TITLE
  File "importlib\metadata\__init__.py", line 548, in from_name importlib.metadata.PackageNotFoundError: No package metadata was found for gpsoauth

### ISSUE THREAD

**Issue by boardshorts** [simon-weber/gpsoauth#45]
I have an app that uses gkeepapi which in turn uses your gpsoauth code.  Stopped working recently with the Google login issue which you fixed. I appreciate your work.

Runs from the IDLE and cmd line but I get this message from the .exe after I have created the .exe using pyinstaller. 

Debugging using Kai's simple example that returns the same message running its .exe. Attached file with console text as I set up and run in a virtual environment using venv to eliminate any other installed system-wide modules. Using Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 22:57:10) [MSC v.1929 32 bit (Intel)] on win32 - all other versions in attached file.

[gpsoauth-metadata-package-missing.txt](https://github.com/simon-weber/gpsoauth/files/8839303/gpsoauth-metadata-package-missing.txt)

**Comment by simon-weber** [comment]
[Going by this](https://pyinstaller.org/en/stable/when-things-go-wrong.html#listing-hidden-imports) I think this may be an issue with how gpsoauth is being packaged with pyinstaller. Is it fixed by `--hidden-import gpsoauth`?

**Comment by boardshorts** [comment]
--hidden-import gpsoauth same error

My app was last packaged Feb 2021 so I went back through the pyinstaller release notes and noticed the changes in the metadata handling in 4.3 (2021-04-16) and 4.4 (2021-07-13) and found the --copy-metadata option. 

so pyinstaller --copy-metadata gpsoauth --onefile --clean TestKeep.py creates an exe that runs without error . Problem solved.

Maybe in the transition from using importlib_metadata to importlib.metadata something was missed?

**Comment by simon-weber** [comment]
Great! Glad to hear it's working.
