### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by 89z** [simon-weber/gpsoauth#47]
I think it would be helpful if you had a code example of the login, either in the readme, or a separate Python file:

https://github.com/simon-weber/gpsoauth/blob/336a02e3d8e14277b06cc6c73ad608fcf5f73a17/gpsoauth/__init__.py#L91-L94

**Comment by simon-weber** [comment]
I pulled the linked example from gmusicapi and simplified it a bit.

To be honest I don't really remember much about the android id and client sig params, so if anyone knows more and wants to fill in those docs, go for it.

**Comment by 89z** [comment]
The Android ID is returned by Google as a fixed64 value. However in subsequent requests, the client is expected to hex encode that value.
