### ISSUE TITLE
Curl

### ISSUE THREAD

**Issue by virtueer** [simon-weber/gpsoauth#50]
Hello i'm nodejs developer and i imlementing your code to nodejs but it not works. I know the problem is about tls connections. Can you provide curl version of making auth request? I can create EncryptedPassword correctly. I need just making request with ciphers also curl

**Comment by simon-weber** [comment]
The project doesn't use curl so I don't know the curl equivalent, but everything you need should be in https://github.com/simon-weber/gpsoauth/blob/master/gpsoauth/__init__.py. You could also set up a debugging proxy to capture an example request.
