### ISSUE TITLE
Error=BadAuthentication

### ISSUE THREAD

**Issue by irainbw** [simon-weber/gpsoauth#54]
When I directly use http to request authurl, the test found that the request body returned Error=BadAuthentication, and I saw that such code was added to the source code 
![image](https://github.com/simon-weber/gpsoauth/assets/44990372/2e0e665c-fe90-48a6-8f74-86559aaeecf0)
and Debugging found that Error=BadAuthentication is no longer returned. I want to create http requests in the way of golang, but I get the result of Error=BadAuthentication. What needs to be adjusted here?Do I need to add any settings?

**Comment by simon-weber** [comment]
My guess would be you'll need to replicate the tls settings you've called out here. I'm not sure how to do that in go.
