### ISSUE TITLE
Error: BadAuthentication

### ISSUE THREAD

**Issue by sagar-kris** [simon-weber/gpsoauth#65]
As outlined in [alternative flow](https://github.com/simon-weber/gpsoauth?tab=readme-ov-file#alternative-flow):

in line 8
`master_token = master_response['Token']`

when I run the script I get the following error
> File "./oauth-token.py", line 8, in <module>
>     master_token = master_response['Token']
>  KeyError: 'Token'

the credentials I'm using are my gmail email, a randomly generated android id (9876ABCD4321EFGH), and my oauth token.

Edit: this is being caused by a BadAuthentication error. here are my package versions

backports.tarfile        1.1.1
cachetools               5.3.3
certifi                  2024.2.2
chardet                  3.0.4
charset-normalizer       3.3.2
future                   1.0.0
gkeepapi                 0.16.0
google-api-core          2.18.0
google-api-python-client 2.127.0
google-auth              2.29.0
google-auth-httplib2     0.2.0
google-auth-oauthlib     1.2.0
googleapis-common-protos 1.63.0
gpsoauth                 1.1.0
httplib2                 0.22.0
idna                     2.10
importlib_metadata       7.1.0
jaraco.classes           3.4.0
jaraco.context           5.3.0
jaraco.functools         4.0.1
keyring                  25.2.0
more-itertools           10.2.0
oauthlib                 3.2.2
pip                      22.2.1
proto-plus               1.23.0
protobuf                 4.25.3
pyasn1                   0.6.0
pyasn1_modules           0.4.0
pycryptodomex            3.20.0
pyparsing                3.1.2
requests                 2.31.0
requests-oauthlib        2.0.0
rsa                      4.9
setuptools               63.2.0
uritemplate              4.1.1
urllib3                  1.25.11
zipp                     3.18.1

**Comment by simon-weber** [comment]
I added a note to the readme so a missing token is less suprising.
