### ISSUE TITLE
How do I use this to access the API of a game?

### ISSUE THREAD

**Issue by tconn87** [simon-weber/gpsoauth#68]
I've been reversing the API for a game for 4 years. I've made progress and given up many times. I'm able to get the master token with this code, but I'm not sure how to proceed. I'm able to see the network traffic using HTTP Toolkit and Wireshark, but I don't see anything that looks like the oauth token. I've gone step-by-step trying to determine how the game typically logs in. It uses Google's Integrity API among other things. The game is Star Wars: Galaxy of Heroes. There's been a website for several years that is able to access game data and perform actions, but (1) they charge for the service (2) it's something I'd like to figure out how to do, and (3) I'm wanting to do something that the service does not do. I asked the owner about it and, understandably, they refused to provide information. Can someone point me in a direction I can take the master token or a website where I can learn a different method to achieve my goal?

also, I'm not familiar with discussion in Github. I guess I'm not able to label my "issue", I'm sorry if asking this here is frowned upon

**Comment by simon-weber** [comment]
Sorry, this library only handles Google auth. Other Google services or specific apps aren't relevant to this repo.
